"""Cerebras correction/explanation/judge tests. HTTP mocked unless RUN_LIVE_LLM_TESTS=1."""

import json
import os

import httpx
import pytest

from backend.llm.base import LLMClient, LLMRetryExhausted, RetryPolicy
from backend.llm.cerebras_client import (
    CEREBRAS_BASE_URL,
    CEREBRAS_CHAT_PATH,
    CEREBRAS_DEFAULT_MODEL,
    correct_sql,
    explain_sql,
    judge,
)

SCHEMA = {
    "orders": {
        "columns": [
            {"name": "id", "type": "integer", "nullable": False},
            {"name": "customer_id", "type": "integer", "nullable": False},
            {"name": "total", "type": "numeric", "nullable": True},
        ],
        "primary_key": ["id"],
        "foreign_keys": [{"column": "customer_id", "ref_table": "customers", "ref_column": "id"}],
    }
}


def _completion(content: str) -> dict:
    return {
        "id": "chatcmpl-test",
        "object": "chat.completion",
        "model": CEREBRAS_DEFAULT_MODEL,
        "choices": [
            {
                "index": 0,
                "message": {"role": "assistant", "content": content},
                "finish_reason": "stop",
            }
        ],
        "usage": {"prompt_tokens": 200, "completion_tokens": 60, "total_tokens": 260},
    }


def _client(handler, **policy_kwargs) -> LLMClient:
    transport = httpx.MockTransport(handler)
    return LLMClient(
        provider="cerebras",
        base_url=CEREBRAS_BASE_URL,
        chat_path=CEREBRAS_CHAT_PATH,
        api_key="csk_test_key_wxyz",
        default_model=CEREBRAS_DEFAULT_MODEL,
        retry_policy=RetryPolicy(base_seconds=0.0, max_seconds=0.0, **policy_kwargs),
        client=httpx.AsyncClient(transport=transport, base_url=CEREBRAS_BASE_URL),
    )


@pytest.mark.asyncio
async def test_correct_sql_success():
    seen = {}

    def handler(request: httpx.Request) -> httpx.Response:
        seen["url"] = str(request.url)
        seen["auth"] = request.headers.get("authorization")
        seen["body"] = json.loads(request.content)
        return httpx.Response(
            200,
            json=_completion(
                json.dumps(
                    {
                        "sql": "SELECT customer_id FROM orders",
                        "reasoning": "no such column client_id; the schema calls it customer_id",
                    }
                )
            ),
        )

    result = await correct_sql(
        "list customer ids",
        SCHEMA,
        failed_sql="SELECT client_id FROM orders",
        error='column "client_id" does not exist',
        client=_client(handler),
    )

    assert seen["url"] == f"{CEREBRAS_BASE_URL}{CEREBRAS_CHAT_PATH}"
    assert seen["auth"] == "Bearer csk_test_key_wxyz"
    assert seen["body"]["response_format"] == {"type": "json_object"}
    assert result.sql == "SELECT customer_id FROM orders"
    assert "customer_id" in result.reasoning
    assert result.raw.usage["total_tokens"] == 260


@pytest.mark.asyncio
async def test_correct_sql_retries_after_429_then_succeeds():
    calls = {"n": 0}

    def handler(request: httpx.Request) -> httpx.Response:
        calls["n"] += 1
        if calls["n"] == 1:
            return httpx.Response(429, headers={"retry-after": "0"}, json={"error": "slow down"})
        return httpx.Response(
            200, json=_completion(json.dumps({"sql": "SELECT 1", "reasoning": "fixed"}))
        )

    result = await correct_sql(
        "q", SCHEMA, failed_sql="SELCT 1", error="syntax error", client=_client(handler)
    )

    assert calls["n"] == 2, "expected exactly one retry after the 429"
    assert result.sql == "SELECT 1"


@pytest.mark.asyncio
async def test_correction_prompt_does_not_disclose_sql_authorship():
    """Independence guard: the corrector must not learn where the SQL came from."""
    seen = {}

    def handler(request: httpx.Request) -> httpx.Response:
        seen["prompt"] = json.loads(request.content)["messages"][0]["content"]
        return httpx.Response(
            200, json=_completion(json.dumps({"sql": "SELECT 1", "reasoning": "x"}))
        )

    await correct_sql("q", SCHEMA, failed_sql="SELECT bad", error="boom", client=_client(handler))

    lowered = seen["prompt"].lower()
    for leak in ("groq", "llama", "same model", "another model", "generated by", "the generator"):
        assert leak not in lowered, f"correction prompt leaked authorship: {leak!r}"


@pytest.mark.asyncio
async def test_explain_sql_returns_plain_text():
    def handler(request: httpx.Request) -> httpx.Response:
        body = json.loads(request.content)
        # Explanation is prose, so JSON mode must be off.
        assert "response_format" not in body
        return httpx.Response(
            200,
            json=_completion(
                "  This counts every order in the table and returns a single number.  "
            ),
        )

    text = await explain_sql(
        "how many orders", "SELECT COUNT(*) FROM orders", client=_client(handler)
    )

    assert text == "This counts every order in the table and returns a single number."


@pytest.mark.asyncio
async def test_judge_success_and_no_authorship_leak():
    seen = {}

    def handler(request: httpx.Request) -> httpx.Response:
        seen["prompt"] = json.loads(request.content)["messages"][0]["content"]
        return httpx.Response(
            200,
            json=_completion(
                json.dumps({"verdict": True, "reasoning": "same rows, only the alias differs"})
            ),
        )

    result = await judge(
        "how many orders",
        gold_sql="SELECT COUNT(*) FROM orders",
        generated_sql="SELECT COUNT(*) AS n FROM orders",
        gold_result_summary="1 row: 42",
        generated_result_summary="1 row: 42",
        client=_client(handler),
    )

    assert result.verdict is True
    assert "alias" in result.reasoning

    lowered = seen["prompt"].lower()
    for leak in ("groq", "cerebras", "llama", "same model", "you wrote", "your own"):
        assert leak not in lowered, f"judge prompt leaked authorship: {leak!r}"


@pytest.mark.asyncio
async def test_judge_retries_after_429_then_succeeds():
    calls = {"n": 0}

    def handler(request: httpx.Request) -> httpx.Response:
        calls["n"] += 1
        if calls["n"] == 1:
            return httpx.Response(429, headers={"retry-after-ms": "5"}, json={"error": "429"})
        return httpx.Response(
            200, json=_completion(json.dumps({"verdict": False, "reasoning": "different filter"}))
        )

    result = await judge(
        "q", "SELECT 1", "SELECT 2", "1 row: 1", "1 row: 2", client=_client(handler)
    )

    assert calls["n"] == 2
    assert result.verdict is False


@pytest.mark.asyncio
async def test_judge_gives_up_after_retry_budget():
    calls = {"n": 0}

    def handler(request: httpx.Request) -> httpx.Response:
        calls["n"] += 1
        return httpx.Response(500, json={"error": "server error"})

    with pytest.raises(LLMRetryExhausted):
        await judge("q", "SELECT 1", "SELECT 2", "a", "b", client=_client(handler, max_retries=2))

    assert calls["n"] == 3


@pytest.mark.asyncio
async def test_fenced_json_is_tolerated():
    """Models emit fenced JSON even under JSON mode; parsing must survive it."""

    def handler(request: httpx.Request) -> httpx.Response:
        fenced = '```json\n{"sql": "SELECT 1", "reasoning": "ok"}\n```'
        return httpx.Response(200, json=_completion(fenced))

    result = await correct_sql("q", SCHEMA, failed_sql="x", error="y", client=_client(handler))
    assert result.sql == "SELECT 1"


@pytest.mark.skipif(
    os.getenv("RUN_LIVE_LLM_TESTS") != "1" or not os.getenv("CEREBRAS_API_KEY"),
    reason="live test; set RUN_LIVE_LLM_TESTS=1 and CEREBRAS_API_KEY",
)
@pytest.mark.asyncio
async def test_live_cerebras_correct_sql():
    result = await correct_sql(
        "list customer ids",
        SCHEMA,
        failed_sql="SELECT client_id FROM orders",
        error='column "client_id" does not exist',
    )

    assert result.sql, "live Cerebras call returned no SQL"
    assert "customer_id" in result.sql.lower()
    print(f"\n[live cerebras] model={result.raw.model} latency={result.raw.latency_ms}ms")
    print(f"[live cerebras] sql={result.sql}")
